package calculator.common;

/**
* calculator/common/CalculatorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Monday, December 30, 2013 4:18:27 o'clock PM CET
*/

public final class CalculatorHolder implements org.omg.CORBA.portable.Streamable
{
  public calculator.common.Calculator value = null;

  public CalculatorHolder ()
  {
  }

  public CalculatorHolder (calculator.common.Calculator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = calculator.common.CalculatorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    calculator.common.CalculatorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return calculator.common.CalculatorHelper.type ();
  }

}
