package calculator.common;


/**
* calculator/common/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Monday, December 30, 2013 4:18:27 o'clock PM CET
*/

public interface CalculatorOperations 
{
  int add (int a, int b);
  int sub (int a, int b);
} // interface CalculatorOperations
